name: Coffee-break

on:
  schedule:
    - cron: '0 0 5 * *'  # This runs at 00:00 UTC on the 5th of every month

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: golang:1.19

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        repository: 'redhat-appstudio/qe-tools'

    - name: Setup Go environment
      uses: actions/setup-go@v5

    - name: Run Test and Send Slack Message
      run: go run main.go coffee-break
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        HACBS_CHANNEL_ID: ${{ secrets.HACBS_CHANNEL_ID }}

    - name: Commit and push if it's not a Pull Request
      run: |
        git config --global --add safe.directory /__w/qe-tools/qe-tools
        git init /__w/qe-tools/qe-tools
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add config/coffee-break/last_week.txt
        git commit -m "Update config/coffee-break/last_week.txt"
        git push origin main -f
