name: release

on:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: wangyoucao577/go-release-action@279495102627de7960cbc33434ab01a12bae144b # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          goversion: "1.22"
          binary_name: qe-tools
          extra_files: config
